# Generated by Django 5.0.1 on 2024-01-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_hashtag_remove_post_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="social_media.hashtag"
            ),
        ),
    ]
